# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: backend

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build and Test with Maven
      run: mvn -B clean package -DskipTests
    - name: Maven Verify
      run: mvn -B clean verify
  
  docker-push: 
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}} 
        DOCKER_PASSWORD:  ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    - name: build docker 
      run: |
        docker build "$GITHUB_WORKSPACE" -f  "Dockerfile" -t pratj97/insurance-backend:${{ github.sha }}
        docker push pratj97/insurance-backend:${{ github.sha }}
      
  



