name: suggestor_ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: python

jobs:
  docker-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD:  ${{secrets.DOCKER_PASSWORD}}
          REPO: ${{secrets.REPO}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: build docker and push (Python script)
        run: |
          docker build "$GITHUB_WORKSPACE/python" -f  "Dockerfile" pratj97/insurance-suggestor:${{ github.sha }}
          docker push pratj97/insurance-suggestor:${{ github.sha }}
