
name: React CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: Frontend/InsuranceApplication

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
#     - run: npm test
#     - run: npm run build
  docker-push: 
      runs-on: ubuntu-latest
      needs: [build]
      steps:
      - uses: actions/checkout@v2
#       - name: Set up JDK 11
#         uses: actions/setup-java@v1
#         with:
#           java-version: 11.0.4
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}} 
          DOCKER_PASSWORD:  ${{secrets.DOCKER_PASSWORD}}
          REPO: ${{secrets.REPO}} 
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: pratj97/insurance-frontend
          tags: v1, latest
          registry: registry-url.io
          dockerfile: Dockerfile.ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
